### ISSUE TITLE
Frequent attribute errors in CloningWidget

### ISSUE THREAD

**Issue by j-andrews7** [GuidoBartoli/sherloq#12]
Getting these every time the CMF tool is run:

```
Traceback (most recent call last):
  File "/mnt/c/Users/Jared/Documents/ImageDups/sherloq/gui/cloning.py", line 148, in cancel
    self.reset()
AttributeError: 'CloningWidget' object has no attribute 'reset'
```

Doesn't really appear to affect function, though I'm finding it pretty easy to freeze up the tool with larger/more complex images.

**Comment by GuidoBartoli** [comment]
Many thanks for pointing it out, it should have been fixed in the latest commit c657ba251c1f400ce92ad7dc7320455083633222.
Let me know if it is working now.

For larger images, use the faster BRISK detector and try to use lower values for *Response* (80% or 70%) and *Matching* (15% or 10%): you could miss some regions, but with less keypoints you should have a faster matching.
However, how large are your images? I can apply the tool to 12 Mpx images and obtain results in under 5 seconds.

**Comment by j-andrews7** [comment]
Cheers, error is indeed no longer present.

Below is an example of an image that takes 100-120 seconds with me using BRISK and the default settings. The image isn't crazy large or even high res, but it does have a lot of similar elements. I know basically nothing about how the algorithms behind the CMF tool work, but my presumption is that those similarities bog things down quite a bit. It also spikes both my CPU and RAM and occasionally disk usage to 100%, which is fine, but I'm not sure if that's to be expected.

![image](https://user-images.githubusercontent.com/10225716/87264723-66591f80-c486-11ea-9d06-8b43ab49c416.png)

I'm using the tool to detect scientific fraud in published works, and you can imagine why using it on images like this might be helpful (fraudulent works often duplicate elements between figure panels with mirroring, rotation, or recoloring).

**Comment by GuidoBartoli** [comment]
> Cheers, error is indeed no longer present.

Good! :+1:

> Below is an example of an image that takes 100-120 seconds with me using BRISK and the default settings. The image isn't crazy large or even high res, but it does have a lot of similar elements. I know basically nothing about how the algorithms behind the CMF tool work, but my presumption is that those similarities bog things down quite a bit. It also spikes both my CPU and RAM and occasionally disk usage to 100%, which is fine, but I'm not sure if that's to be expected.

Yep, that kind of patterns generate LOTS of keypoints so CPU and RAM spike because of intense computation, while disk can go to 100% because the RAM has filled up and the operating system is using virtual memory on disk for swapping (if you fill up virtual memory too, the program is likely to be killed by the OS).

To cope with this kind of images I'm thinking about adding a "Reduction" parameter where you can specify the subsampling amount for the algorithm to work on scaled version of the original image. My hope is to provide a tradeoff between accuracy and speed in this way, so if matching accuracy is not too much degraded, I will add it in the next commit.

> I'm using the tool to detect scientific fraud in published works, and you can imagine why using it on images like this might be helpful (fraudulent works often duplicate elements between figure panels with mirroring, rotation, or recoloring).

Also the user @under-score applies CMF to detect such kind of manipulations... I did not expect so much interest in this, so I'm glad my tool can be of any help in this forensic application! :nerd_face:

**Comment by j-andrews7** [comment]
`Also the user @under-score applies CMF to detect such kind of manipulations... I did not expect so much interest in this, so I'm glad my tool can be of any help in this forensic application! 🤓`

It's honestly a huge help. Generally, I find things by eye, but it's great for spot checking large, complex images like the above where mirroring and rotated elements can be really hard to catch. The **Enhancing Magnifier** tool along with the **PCA Projection** tools have also been super helpful for detecting spliced images that don't look quite right.

Now I just need a way to automate the process to run with multiple sets of parameters on the same image, ignore all text, and save the output from the command line so that I can just flip through output for manual review 😈

**Comment by under-score** [comment]
I have been playing with auto export pictures from PDFs, following CMF detection by sensitive and less sensitive parameter setting, excluding keypoints that match Tesseract OCR but went now back to @GuidoBartoli 's Sherloq to learn more about the different methods. Postponed also the idea of creating a web interface as any free online service would need more CPUs than I could pay for.

**Comment by j-andrews7** [comment]
I've been using `pdfminer.six` for automatic export of images from PDF, which works well. But the masking of text is what slows me down to the point where it's usually quicker to just eyeball it or screen cap the image in question while excluding labels if it's too difficult to see by eye but I suspect something's off.

The ideal workflow would be to automatically download PDFs via a cron job or whatever  (via NCBI's API), scrape images via `pdfminer.six`, run Sherloq tools, and have flags generated for manual review if the CMF tool has hits, in which case I'd probably have it generate a few other figures too (**Enhancing Magnifier** images chief among them).

**Comment by GuidoBartoli** [comment]
Since you mentioned it and if you did not notice yet, resizing the **Enhancing Magnifier** window affects the processed region, so you can apply _Histogram Equalization_ or _Contrast Boost_ to smaller or larger image parts.
