### ISSUE TITLE
Bash problem

### ISSUE THREAD

**Issue by crazyreverser** [GuidoBartoli/sherloq#24]
removed

**Comment by GuidoBartoli** [comment]
Mmmh it seems caused from not using `bash` as the default shell for this version of MacOS, but I cannot reproduce it here, because I have another version. I will write instructions for `zsh` as soon as I can try it, but in the meanwhile you can take a look [here](https://www.howtogeek.com/444596/how-to-change-the-default-shell-to-bash-in-macos-catalina/).

**Comment by crazyreverser** [comment]
/
