### ISSUE TITLE
Output formats?

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#28]
Is there - or could there be - a way to output formats other than PNG for processed images, e.g. JPEG, PDF, .npy..? Thanks!

**Comment by GuidoBartoli** [comment]
Hi, PNG was chosen because it is a lossless format and preserves the original pixel values. Using a lossy format like JPG risks introducing artifacts and distortions that are undesirable in forensics. However, I can maintain PNG as default and however let the user choose a lossy format at his/her risk, thanks for suggestion, I added it to the next development!

**Comment by jtlz2** [comment]
@GuidoBartoli Indeed - and your solution is a welcome one! Thanks again
