### ISSUE TITLE
Issue with Splicing Probability Heatmap

### ISSUE THREAD

**Issue by jtlz2** [GuidoBartoli/sherloq#30]
In the image below, there are some red circular artifacts. What is the significance of these? Is there a way to mitigate them to see what the underlying heatmap looks like?

![heatmap](https://user-images.githubusercontent.com/3842318/107019765-babd4700-67aa-11eb-8f67-b551ef5d39ff.png)

Thanks!

**Comment by GuidoBartoli** [comment]
Those regions appear where there is not enough detail (too low brightness variance) to determine the splicing probability. You can see them also in the original **Noiseprint** description [here](http://www.grip.unina.it/research/83-multimedia_forensics/107-noiseprint.html) (they are shown as blue patches because the colormap is inverted with respect to Sherloq). Does this make sense for your input image?

**Comment by jtlz2** [comment]
Yes that makes sense in principle and thanks for the helpful link.

Would anything reduce the contribution from these regions / enhance the signal-to-noise/combine bins in order to increase the surface brightness?

Yep I saw the padding effect.

**Comment by GuidoBartoli** [comment]
> Would anything reduce the contribution from these regions / enhance the signal-to-noise/combine bins in order to increase the surface brightness?

I don't know if I understood your question correctly, however these regions are completely ignored at the level of classifications and by default receive probability 0, so they result as "not tampered" at all.

**Comment by jtlz2** [comment]
Put another way, is there a way to reduce the size (diameter) of these regions?
Thanks!

**Comment by GuidoBartoli** [comment]
Well, they are dependent on the content of the image and generally appear in "flat" areas with no texture. If you want them to disappear, you have to alter the image, but maybe that's not what you want?
