### ISSUE TITLE
Is there any scientific guide to tools?

### ISSUE THREAD

**Issue by masouduut94** [GuidoBartoli/sherloq#40]
I am very amazed with all the tools provided for image forensics in this repo which certainly got a lot of time to research.

I opened this issue because I cant find good resource that can provide full description and mathematical theories behind all the tools that have been used here like error level analysis or luminance gradient and etc.

please provide some information and mathematical description behind the developed tools and include it in the README.md file.

Thanks

**Comment by GuidoBartoli** [comment]
Hi @masouduut94, thanks, I'm happy for my tools to be of any help in forensic research! :smiley: 
You're right, tool documentation is still missing in Sherloq because I have yet to finish writing it and decide how to include it (contextual help, hideable lateral dock, dedicated pages on Github, ...). It certainly is the next main thing to do, I hope to have time to complete it in some months. Sorry, but I can only dedicate spare time to Sherloq... :disappointed:
