### ISSUE TITLE
BRISK versus NoisePrint

### ISSUE THREAD

**Issue by under-score** [GuidoBartoli/sherloq#8]
NoisePrint is a great new feature.

Here is a quick photoshopped file (content aware fill of the stone bottom right) 

that is perfectly recognized by BRISK while the noise heatmap is quite off target...

![Bildschirmfoto 2020-07-04 um 13 45 51](https://user-images.githubusercontent.com/2796454/86511840-26969600-bdfd-11ea-9d68-7ee0f4a2978e.jpg)

**Comment by GuidoBartoli** [comment]
That makes sense: **Content Aware Fill** uses existing patterns to cover a specified area, so *BRISK* can be useful to detect such repetitions, while *NoisePrint* is used to discover noise inconsistencies, which theoretically do not exist in the "synthetized" region, because copied patterns contain the same noise as the whole image.
In this case, however, it seems "suspicious" about the upper right region (the big gray stone), so maybe it contains a different kind of noise respect to the rest of the image, this could be investigated and cross-checked with some other tools.

**Comment by under-score** [comment]
Agree (although the grey stone is definitely some false positive - my own picture, have even the Nikon raw file here).

**Comment by GuidoBartoli** [comment]
Yeah, that can be... if you read the original [NoisePrint paper](https://arxiv.org/pdf/1808.08396.pdf) at page 9, figure 9 shows some false positives and this is the explanation:

```
Problems are mostly due to strongly textured regions,
whose leaks in the noise residual are interpreted as an alien noiseprint.
```

**Comment by under-score** [comment]
I think you could write a textbook :-)

**Comment by GuidoBartoli** [comment]
Thanks, I hope to begin working soon on the online help to provide as much information as possible :-)
