### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by under-score** [GuidoBartoli/sherloq#9]
My experience is more with PHP/JS but  I am not convinced to marry both worlds by some
`shell_exec('python hello.py');`
Isn't there any Django / Turbogears programmer out there to jump in?

**Comment by GuidoBartoli** [comment]
I think the best performance would be achieved by implementing native JS code running similarly to [Forensically](https://29a.ch/photo-forensics/#forensic-magnifier), but I admit I have not enough experience in web development to do that, so any volunteer is really welcome, because a web interface would be ideal to be cross-platform and lightweight.

**Comment by under-score** [comment]
Agree. Unfortunately Forensically obfuscated all code and even removed the accompanying github site. 
At the very end, a lightweight webinterface would make this a website that every journalist would have to visit.

**Comment by GuidoBartoli** [comment]
Yep, I know, it started as an open-source project, but turned to be almost closed-source.. :(
If you accidentally get in touch with any volunteer, please let me know!

**Comment by under-score** [comment]
Promised. There are excellent JS programmers out there (look at the incredible http://viliusle.github.io/miniPaint ) although I think the python libraries shouldn't be recreated in JS.
